### ISSUE TITLE
Implement filtering

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/cms-event-registration#28]
The "browse by" functionality isn't currently wired up. We'll need to consider how we'll want users to be able to filter.

![image](https://user-images.githubusercontent.com/9009552/79382760-065be700-7f32-11ea-85a7-4f6f0e5a9ccb.png)

cc @achong07

**Comment by achong07** [comment]
These are a few things that I think could be useful to add to this filter option:

- Type (Webinar, Conference, Class, etc.)
- Location (maybe show a filter by 25 mile radius) 
- Price (Free/Paid could be a good place to start for now)
- Category/Topic (tag-based)

I think the first two would be the best to start with, and I can do some mocks for them. How do folks feel about this?

**Comment by kemmerle** [comment]
Hi @achong07, @anthmatic,

I'm currently working on hooking up the Browse By function, so that users can filter by a type (webinar, conference, etc) for each event, just as Amanda suggested above. I totally agree with Amanda that Type and Location seem like the best categories to start out with, and I'd love to see some mocks for those. 

 I'm going to try to push a draft PR by tomorrow (perhaps Monday), so people can take a look and give some feedback. And of course, I can change things up, once Amanda has a chance to do some mocks :)

**Comment by achong07** [comment]
@kemmerle what do you think of this for the filtering view?
https://hubspot.invisionapp.com/share/V8WK8447MXS#/414106746_Browse_By_Filter

Went with a simple checkbox filter for both type/location. I'm thinking location will only populate the values that exist in your table, otherwise it won't show up as a filter. Same with type filter.

If you arrow to the right you can see the filtered tags show up in the gray bar to indicate what you're filtering by. Let me know what you think!

**Comment by achong07** [comment]
Also added mockups for what this should look like on mobile (use right arrow keys to thumb through): https://hubspot.invisionapp.com/share/V8WK8447MXS#/414123432_Mobile_-_Filter

I think it'd be nifty if the filters were in some sort of accordion that you could expand/collapse. Thinking they should be collapsed on default, and then you can tap them to open.

**Comment by kemmerle** [comment]
Hi @achong07, I think that the mocks are looking great :) I will get on this right now.
