### ISSUE TITLE
Add support for different hubdb table names

### ISSUE THREAD

**Issue by ajlaporte** [HubSpot/cms-event-registration#91]
Right now where we have it, the `yarn create-table --portal <portalId>` will auto-create a HubDB table with the name `events`. This means that if the customer has an existing table already with that name in the list of tables, they will not be able to have this created and it will error out. Many portals may already have a table with that name in it and have rolled their own version of an events system.

Can we offer the option for users to supply a table name upon creation?

**Comment by kemmerle** [comment]
Instead of offering users an option to supply a table name, I'd suggest that we go for a much simpler solution: Let's rename the table `events` + a UUID (ie: `events-d80c8934-3ccd-4e8b-b598-16669c3a728e`). This would guarantee that the events table in our app would have a *completely unique* name (it's actually impossible to have two identical UUID's). 

There are drawbacks to users generating the table name themselves:
-Updates will be more difficult,
-Support will be more difficult (because we won't know what the table is called),
-Someone will make a typo when entering the name and won't understand why things don't work,
-Someone may change the name of the table afterwards, and their events will disappear,
etc. 

I think a UUID solves this issue with no downsides. 

cc @ajlaporte @levinkeo @anthmatic

**Comment by levinkeo** [comment]
To close the loop for future reference, we talked offline about his and ended up opting for reserving a hs-specific namespace over using a UUID. Since there's precedent for requiring folks to navigate around "reserved" properties, fieldnames, etc. in HubSpot, it makes sense to adopt something like `hs_events` (similar to `hs_path` via HubDB column names).

It's definitely not as airtight as @kemmerle's suggestion, but given the readability we'd maintain in the code, it felt like a decent compromise. We can always circle back to something with more safeguards against collisions if it becomes an issue later.

I'm happy to grab this and change the `events` -> `hs_events`
